### ISSUE TITLE
There is no soth package

### ISSUE THREAD

**Issue by hihixuyang** [diogoalmeida/sarafun_bt#11]

**Comment by diogoalmeida** [comment]
Hi! I hope that means that you found the soth package?

**Comment by hihixuyang** [comment]
Hi, Thx a lot! I have fixed these problems.

**Comment by hihixuyang** [comment]
Hi @diogoalmeida ! When I followed your setup flow, I found there is another online_generation package that you have not mentioned.

**Comment by diogoalmeida** [comment]
Yes, I am sorry for that. These packages target my EU project, where that package is a given. I can change the README later. Ideally, I would make the package independent of the soth package, but I require it for one of the demos. 

Let me know if you're interested in using this for integrating a behavior tree into your ROS system, I might be able to offer you some help.

**Comment by hihixuyang** [comment]
Hi, @diogoalmeida. Thx a lot ! I follow your package and your former research colleague Michele Colledanchise, I want to modify and integrate your package into my flight control ros system.

**Comment by hihixuyang** [comment]
My email address is yangxu@u.nus.edu. If you can share some useful files for help.
