### ISSUE TITLE
About the catkin_make problem

### ISSUE THREAD

**Issue by hihixuyang** [diogoalmeida/sarafun_bt#12]
Hi, @diogoalmeida 

I found a problem when catkin_make process.
<img width="368" alt="20170718194457" src="https://user-images.githubusercontent.com/24733393/28315615-cb148694-6bf1-11e7-9536-e63824260fe8.png">

**Comment by diogoalmeida** [comment]
Hi,

I'll need you to be a bit more specific, could you paste the whole terminal output?

Thanks!

**Comment by hihixuyang** [comment]
Hi, @diogoalmeida 

Please see this fig, I have deleted the online package.

<img width="500" alt="20170718200218" src="https://user-images.githubusercontent.com/24733393/28316131-1dbba722-6bf4-11e7-856f-5f478c7dadc3.png">

**Comment by diogoalmeida** [comment]
Those errors seem to  indicate that you're having issues linking to ROS. Which version of ROS are you using? Can you compile other packages?

**Comment by hihixuyang** [comment]
Hi, I have ros kinetic and I can compile my uav ros package successfully.

**Comment by diogoalmeida** [comment]
If you go to the ``~/catkin_bt`` and run ``rm -rf build devel install`` and then compile, will you have the same error?

**Comment by hihixuyang** [comment]
Hi, the error seems the same.

<img width="503" alt="20170718205932" src="https://user-images.githubusercontent.com/24733393/28318120-2af13f1c-6bfc-11e7-9250-47956309ebde.png">
<img width="502" alt="20170718205959" src="https://user-images.githubusercontent.com/24733393/28318126-2e971196-6bfc-11e7-890e-ecc0a58ecffd.png">

**Comment by diogoalmeida** [comment]
I cannot replicate it in my machine... when I create a new workspace and follow the compilation instructions in the README I do not get that linking error. Which compiler are you using? 

It might be due to the fact that you're using kinetic: [see here](http://answers.ros.org/question/234322/linker-error-on-ros-kinetic-ubuntu-1604/)

**Comment by hihixuyang** [comment]
Thx a lot! I found most of the errors happened during compiling the demo package.

**Comment by hihixuyang** [comment]
All of the problems are related to PlaceDummy.cpp

**Comment by diogoalmeida** [comment]
From the root of your workspace you can try to do ``touch src/sarafun_bt/sarafun_bt_demo/CATKIN_IGNORE`` and see if that helps compiling.

**Comment by hihixuyang** [comment]
My friend and I find it maybe the version problems that causes the ros lib can not be linked

**Comment by hihixuyang** [comment]
Hi @diogoalmeida , there is no /sarafun_bt_demo package

**Comment by diogoalmeida** [comment]
Oops, it should be ``sarafun_bt_nodes_test``. Basically, the package that contains ``PlaceDummy.cpp``

**Comment by hihixuyang** [comment]
Hi, @diogoalmeida  thx! I have solved this problem and find it runs with time consuming and I wanna read and refine it carefully.

**Comment by diogoalmeida** [comment]
Hey, glad to read that.

Could you clarify how you fixed the problem? Is there something I need to change in the package? 

What do you mean by "find it runs with time consuming"? What are you running?

**Comment by hihixuyang** [comment]
Hi, I remove the packages of  sarafun_bt and sarafun_bt_nodes_test, my friend found your version needs to be modified by us to fit for our waypoints mission.

**Comment by diogoalmeida** [comment]
Very well! Good luck for your project!

**Comment by hihixuyang** [comment]
Thanks a lot! @diogoalmeida
